#!/bin/bash

# This script takes in a list of paths and outputs a list of top-level project directories,
# e.g. directories with `Project.toml` files in them.

declare -A PROJECT_DIRS

# `f` is the full path of each file that was changed
for f in "$@"; do
    while [[ "${f}" == lib/* ]]; do
        if [[ -f "${f}/Project.toml" ]]; then
            # `f` must be a project in the top-level of `lib` directory
            if [[ $(dirname "${f}") == lib ]]; then
                PROJECT_DIRS["${f}"]=1
                break
            fi
        fi
        # update `f` to the path of its parent directory
        f="$(dirname "${f}")"
    done
done

echo "${!PROJECT_DIRS[@]}"
