steps:
  - label: ":pipeline::julia: Launch JuliaCon 2023 Talk Demo Pipelines!"
    commands:
      - buildkite-agent pipeline upload .buildkite/demo-1/pipeline.yml
      - buildkite-agent pipeline upload .buildkite/demo-2/pipeline.yml

    agents:
      sandbox.jl: true
