steps:
  - label: ":pipeline::julia: Launch JuliaCon 2023 Talk Demo Pipelines!"
    commands:
      - buildkite-agent pipeline upload .buildkite/demo-1-forerunner/pipeline.yml
      - buildkite-agent pipeline upload .buildkite/demo-2-sandbox/pipeline.yml
      - buildkite-agent pipeline upload .buildkite/demo-3-jack/pipeline.yml

    agents:
      sandbox.jl: true
      queue: juliaecosystem
