steps:
  - label: "Running workflows in reproducible, sandboxed environments"
      plugins:
        - JuliaCI/julia#v1

        - staticfloat/sandbox#v1:
            rootfs_url: "https://github.com/ven-k/Placeholder/releases/download/v0.30.0/super_set_image.x86_64.tar.gz"
            rootfs_treehash: "088a99926b4bfde227ddcf49f239ed484f013cbf"
            workspaces:
              # Include `/cache` so that `julia` install can properly cache its Julia downloads
              - "/cache:/cache"
              # Include `~/.ssh` so that we get the pre-filled `known_hosts` file
              - "${HOME}/.ssh:/root/.ssh"

        - JuliaCI/julia#v1

        - JuliaCI/julia-test#v1

      agents:
        os: "linux"
        sandbox.jl: true
