steps:
  - label: "Showcase secrets decrypting"
    # Note, if this is a child pipeline launched by the webUI config, you MUST receive this
    # value from the parent pipeline in order to decrypt secrets.  Further note, do NOT list
    # this environment variable as a top-level key within ANY `.yaml` file, as this will
    # cause the value to be appended to all future pipelines!
    env:
      BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET: ${BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET?}
    plugins:
    - staticfloat/cryptic#v2:
        files:
            # This file is actually only stored as `secret_message.txt.encrypted` in the repo,
            # and `cryptic` will create the `secret_message.txt` file from it, when it decrypts
            # in its `post-checkout` step.  It is recommended to `.gitignore` the decrypted file
            # both for security, to prevent accidental check-in, and so that after decryption,
            # `git` still thinks the repository state is clean.
            - ".buildkite/demo-6-cryptic/secret_message.txt"
        variables:
            - AWS_CREDENTIALS="U2FsdGVkX1/1XkkZ5pGUg/B3EEkjd8/BMAztYcXRGGylRJnxcKSN4OJi1xlS8eNZ"
    commands: |
        # When writing bash scripts in these .yml files, remember that the buildkite-agent
        # does variable interpolation itself, so you need to double-escape your dollar signs
        # when referring to a bash variable that is defined at runtime:
        echo "+++ Decryption Proof"
        echo "To prove that we decrypted 'AWS_CREDENTIALS', here it is: $${AWS_CREDENTIALS}"
        echo "To prove that we decrypted secret_message.txt, here it is:"
        cat ./.buildkite/demo-6-cryptic/secret_message.txt
    agents:
      cryptic_capable: true
      queue: juliacon2023
