steps:
  - label: ":julia: Formatting Check"

    plugins:
      - JuliaCI/julia#v1:
          version: "1.8"

    commands:
      - julia --color=yes -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="1.0.34"))'
      - julia --color=yes -e 'using JuliaFormatter; format(".", verbose=true)'
      - julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String;
          if out !== ""
              @error("Some files have not been formatted !!!");
              write(stdout, out);
              exit(1);
          end'

    agents:
      sandbox_capable: true
      queue: juliacon2023
