steps:
  - label: ":bucket: jack: Install xz via JLLs"
    agents:
      os: linux
      sandbox_capable: true
      queue: "juliacon2023"

    plugins:
      - JuliaCI/julia#v1:
          version: 1
      - JuliaCI/jack:
          install:
            - "XZ_jll"
    commands:
      echo "+++ xz --version"
      xz --version
