steps:
  - label: "tracy: Use tracy to trace execution"
    plugins:
      - JuliaCI/julia#v1:
          version: 1
      - staticfloat/tracy:
          trace: test
      # We use the "julia-test" plugin to do the actual demo
      - JuliaCI/julia-test#v1:
          project: .buildkite/demo-5-tracy
    # Upload all tracy artifacts
    artifacts:
      - "*.trace"
      - capture_agent.log
    agents:
      arch: x86_64
      os: linux
      queue: juliacon2023
